# Docs: https://github.com/Azure/webapps-deploy
# More Azure GitHub Actions: https://github.com/Azure/actions

name: Build and deploy React app to Azure Web App - ucitms3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm ci --force
          npm run build

      - name: Upload production build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ucitms3'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_77136B92C16749EA8C5DA997F59B5A28 }}
          package: ./build
